hunav_loader:
  ros__parameters:
    map: map
    publish_people: true
    agents:
    - worker1
    - worker2
    worker1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 2.8
        y: -0.35
        z: 1.25
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
      - g0
      - g1
      - g2
      - g3
      - g4
      - g5
      - g6
      - g7
      - g8
      - g9
      - g10
      - g11
      - g12
      - g13
      - g14
      - g15
      - g16
      - g17
      - g18
      - g19
      - g20
      - g21
      - g22
      - g23
      - g24
      - g25
      - g26
      - g27
      - g28
      - g29
      - g30
      - g31
      - g32
      - g33
      - g34
      - g35
      - g36
      - g37
      - g38
      - g39
      - g40
      - g41
      - g42
      - g43
      - g44
      - g45
      - g46
      - g47
      - g48
      - g49
      - g50
      - g51
      - g52
      - g53
      - g54
      - g55
      - g56
      - g57
      - g58
      - g59
      - g60
      - g61
      - g62
      - g63
      - g64
      - g65
      - g66
      - g67
      - g68
      - g69
      - g70
      - g71
      - g72
      - g73
      - g74
      - g75
      - g76
      - g77
      - g78
      - g79
      - g80
      - g81
      - g82
      - g83
      - g84
      - g85
      - g86
      - g87
      - g88
      - g89
      - g90
      - g91
      - g92
      - g93
      - g94
      g0:
        x: 2.8
        y: -0.35
        h: 1.25
      g1:
        x: 1.75
        y: -0.35
        h: 1.25
      g2:
        x: 0.8
        y: -0.35
        h: 1.25
      g3:
        x: -0.1
        y: -0.35
        h: 1.25
      g4:
        x: -0.1
        y: -0.35
        h: 1.25
      g5:
        x: -0.1
        y: -1.25
        h: 1.25
      g6:
        x: -0.1
        y: -2.15
        h: 1.25
      g7:
        x: -0.1
        y: -3.05
        h: 1.25
      g8:
        x: -0.1
        y: -3.95
        h: 1.25
      g9:
        x: -0.1
        y: -3.95
        h: 1.25
      g10:
        x: -0.1
        y: -3.95
        h: 1.25
      g11:
        x: -0.1
        y: -3.05
        h: 1.25
      g12:
        x: -0.1
        y: -3.95
        h: 1.25
      g13:
        x: -0.1
        y: -3.05
        h: 1.25
      g14:
        x: -0.1
        y: -3.95
        h: 1.25
      g15:
        x: -0.1
        y: -3.95
        h: 1.25
      g16:
        x: -0.1
        y: -3.05
        h: 1.25
      g17:
        x: -0.1
        y: -2.15
        h: 1.25
      g18:
        x: -0.1
        y: -1.25
        h: 1.25
      g19:
        x: -0.1
        y: -0.35
        h: 1.25
      g20:
        x: -0.1
        y: 0.5
        h: 1.25
      g21:
        x: -0.1
        y: 1.3
        h: 1.25
      g22:
        x: -0.1
        y: 2.1
        h: 1.25
      g23:
        x: -0.1
        y: 2.1
        h: 1.25
      g24:
        x: -0.1
        y: 1.3
        h: 1.25
      g25:
        x: -0.1
        y: 2.1
        h: 1.25
      g26:
        x: -0.1
        y: 1.3
        h: 1.25
      g27:
        x: -0.1
        y: 2.1
        h: 1.25
      g28:
        x: -0.1
        y: 2.1
        h: 1.25
      g29:
        x: -0.1
        y: 3.0
        h: 1.25
      g30:
        x: -0.1
        y: 3.95
        h: 1.25
      g31:
        x: -0.1
        y: 3.95
        h: 1.25
      g32:
        x: -0.1
        y: 3.0
        h: 1.25
      g33:
        x: -0.1
        y: 3.95
        h: 1.25
      g34:
        x: -0.1
        y: 3.0
        h: 1.25
      g35:
        x: -0.1
        y: 3.95
        h: 1.25
      g36:
        x: -0.1
        y: 3.95
        h: 1.25
      g37:
        x: -0.1
        y: 4.9
        h: 1.25
      g38:
        x: -0.1
        y: 5.85
        h: 1.25
      g39:
        x: -0.1
        y: 6.8
        h: 1.25
      g40:
        x: -0.9
        y: 6.8
        h: 1.25
      g41:
        x: -1.6
        y: 6.8
        h: 1.25
      g42:
        x: -2.3
        y: 6.8
        h: 1.25
      g43:
        x: -4.4
        y: 6.8
        h: 1.25
      g44:
        x: -4.4
        y: 6.8
        h: 1.25
      g45:
        x: -2.3
        y: 6.8
        h: 1.25
      g46:
        x: -1.6
        y: 6.8
        h: 1.25
      g47:
        x: -0.9
        y: 6.8
        h: 1.25
      g48:
        x: -0.1
        y: 6.8
        h: 1.25
      g49:
        x: 0.8
        y: 6.8
        h: 1.25
      g50:
        x: 1.75
        y: 6.8
        h: 1.25
      g51:
        x: 1.75
        y: 6.8
        h: 1.25
      g52:
        x: 0.8
        y: 6.8
        h: 1.25
      g53:
        x: -0.1
        y: 6.8
        h: 1.25
      g54:
        x: -0.1
        y: 6.8
        h: 1.25
      g55:
        x: -0.1
        y: 5.85
        h: 1.25
      g56:
        x: -0.1
        y: 6.8
        h: 1.25
      g57:
        x: -0.1
        y: 5.85
        h: 1.25
      g58:
        x: -0.1
        y: 6.8
        h: 1.25
      g59:
        x: -0.1
        y: 6.8
        h: 1.25
      g60:
        x: -0.1
        y: 5.85
        h: 1.25
      g61:
        x: -0.1
        y: 4.9
        h: 1.25
      g62:
        x: -0.1
        y: 3.95
        h: 1.25
      g63:
        x: -0.1
        y: 3.0
        h: 1.25
      g64:
        x: -0.1
        y: 2.1
        h: 1.25
      g65:
        x: -0.1
        y: 1.3
        h: 1.25
      g66:
        x: -0.1
        y: 0.5
        h: 1.25
      g67:
        x: -0.1
        y: -0.35
        h: 1.25
      g68:
        x: -0.1
        y: -1.25
        h: 1.25
      g69:
        x: -0.1
        y: -2.15
        h: 1.25
      g70:
        x: -0.1
        y: -3.05
        h: 1.25
      g71:
        x: -0.1
        y: -3.95
        h: 1.25
      g72:
        x: -0.1
        y: -4.85
        h: 1.25
      g73:
        x: -0.1
        y: -5.8
        h: 1.25
      g74:
        x: 0.8
        y: -5.8
        h: 1.25
      g75:
        x: 1.75
        y: -5.8
        h: 1.25
      g76:
        x: 2.8
        y: -5.8
        h: 1.25
      g77:
        x: 2.8
        y: -5.8
        h: 1.25
      g78:
        x: 1.75
        y: -5.8
        h: 1.25
      g79:
        x: 0.8
        y: -5.8
        h: 1.25
      g80:
        x: -0.1
        y: -5.8
        h: 1.25
      g81:
        x: -0.1
        y: -5.8
        h: 1.25
      g82:
        x: -0.1
        y: -6.75
        h: 1.25
      g83:
        x: -0.1
        y: -6.75
        h: 1.25
      g84:
        x: -0.1
        y: -6.75
        h: 1.25
      g85:
        x: -0.1
        y: -5.8
        h: 1.25
      g86:
        x: -0.1
        y: -4.85
        h: 1.25
      g87:
        x: -0.1
        y: -3.95
        h: 1.25
      g88:
        x: -0.1
        y: -3.05
        h: 1.25
      g89:
        x: -0.1
        y: -2.15
        h: 1.25
      g90:
        x: 0.8
        y: -2.15
        h: 1.25
      g91:
        x: 1.75
        y: -2.15
        h: 1.25
      g92:
        x: 2.8
        y: -2.15
        h: 1.25
      g93:
        x: 3.8
        y: -2.15
        h: 1.25
      g94:
        x: 2.8
        y: -0.35
        h: 1.25
    worker2:
      id: 2
      skin: 4
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 2
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -0.1
        y: -5.8
        z: 1.25
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
      - g0
      - g1
      - g2
      - g3
      - g4
      - g5
      - g6
      - g7
      - g8
      - g9
      - g10
      - g11
      - g12
      - g13
      - g14
      - g15
      - g16
      - g17
      - g18
      - g19
      - g20
      - g21
      - g22
      - g23
      - g24
      - g25
      - g26
      - g27
      - g28
      - g29
      - g30
      - g31
      - g32
      - g33
      - g34
      - g35
      - g36
      - g37
      - g38
      - g39
      - g40
      - g41
      - g42
      - g43
      - g44
      - g45
      - g46
      - g47
      - g48
      - g49
      - g50
      - g51
      - g52
      - g53
      - g54
      - g55
      - g56
      - g57
      - g58
      - g59
      - g60
      - g61
      - g62
      - g63
      - g64
      - g65
      - g66
      g0:
        x: -0.1
        y: -5.8
        h: 1.25
      g1:
        x: -0.1
        y: -6.75
        h: 1.25
      g2:
        x: -0.1
        y: -6.75
        h: 1.25
      g3:
        x: -0.1
        y: -5.8
        h: 1.25
      g4:
        x: -0.1
        y: -6.75
        h: 1.25
      g5:
        x: -0.1
        y: -5.8
        h: 1.25
      g6:
        x: -0.1
        y: -6.75
        h: 1.25
      g7:
        x: -0.1
        y: -6.75
        h: 1.25
      g8:
        x: -0.1
        y: -5.8
        h: 1.25
      g9:
        x: -0.1
        y: -4.85
        h: 1.25
      g10:
        x: -0.1
        y: -3.95
        h: 1.25
      g11:
        x: -0.1
        y: -3.95
        h: 1.25
      g12:
        x: -0.1
        y: -4.85
        h: 1.25
      g13:
        x: -0.1
        y: -3.95
        h: 1.25
      g14:
        x: -0.1
        y: -4.85
        h: 1.25
      g15:
        x: -0.1
        y: -3.95
        h: 1.25
      g16:
        x: -0.1
        y: -3.95
        h: 1.25
      g17:
        x: -0.1
        y: -3.05
        h: 1.25
      g18:
        x: -0.1
        y: -2.15
        h: 1.25
      g19:
        x: -0.1
        y: -1.25
        h: 1.25
      g20:
        x: -0.1
        y: -1.25
        h: 1.25
      g21:
        x: -0.1
        y: -2.15
        h: 1.25
      g22:
        x: -0.1
        y: -2.15
        h: 1.25
      g23:
        x: -0.1
        y: -1.25
        h: 1.25
      g24:
        x: -0.1
        y: -2.15
        h: 1.25
      g25:
        x: -0.1
        y: -1.25
        h: 1.25
      g26:
        x: -0.1
        y: -2.15
        h: 1.25
      g27:
        x: -0.1
        y: -2.15
        h: 1.25
      g28:
        x: -0.1
        y: -1.25
        h: 1.25
      g29:
        x: -0.1
        y: -0.35
        h: 1.25
      g30:
        x: -0.1
        y: 0.5
        h: 1.25
      g31:
        x: -0.1
        y: 1.3
        h: 1.25
      g32:
        x: -0.1
        y: 2.1
        h: 1.25
      g33:
        x: -0.1
        y: 3.0
        h: 1.25
      g34:
        x: -0.1
        y: 3.95
        h: 1.25
      g35:
        x: -0.1
        y: 3.95
        h: 1.25
      g36:
        x: -0.1
        y: 3.0
        h: 1.25
      g37:
        x: -0.1
        y: 3.95
        h: 1.25
      g38:
        x: -0.1
        y: 3.0
        h: 1.25
      g39:
        x: -0.1
        y: 3.95
        h: 1.25
      g40:
        x: -0.1
        y: 3.95
        h: 1.25
      g41:
        x: -0.1
        y: 4.9
        h: 1.25
      g42:
        x: -0.1
        y: 5.85
        h: 1.25
      g43:
        x: -0.1
        y: 6.8
        h: 1.25
      g44:
        x: -0.1
        y: 7.8
        h: 1.25
      g45:
        x: -0.1
        y: 7.8
        h: 1.25
      g46:
        x: -0.1
        y: 6.8
        h: 1.25
      g47:
        x: -0.1
        y: 5.85
        h: 1.25
      g48:
        x: -0.1
        y: 4.9
        h: 1.25
      g49:
        x: -0.1
        y: 4.9
        h: 1.25
      g50:
        x: -0.1
        y: 5.85
        h: 1.25
      g51:
        x: -0.1
        y: 4.9
        h: 1.25
      g52:
        x: -0.1
        y: 5.85
        h: 1.25
      g53:
        x: -0.1
        y: 4.9
        h: 1.25
      g54:
        x: -0.1
        y: 4.9
        h: 1.25
      g55:
        x: -0.1
        y: 3.95
        h: 1.25
      g56:
        x: -0.1
        y: 3.0
        h: 1.25
      g57:
        x: -0.1
        y: 2.1
        h: 1.25
      g58:
        x: -0.1
        y: 1.3
        h: 1.25
      g59:
        x: -0.1
        y: 0.5
        h: 1.25
      g60:
        x: -0.1
        y: -0.35
        h: 1.25
      g61:
        x: -0.1
        y: -1.25
        h: 1.25
      g62:
        x: -0.1
        y: -2.15
        h: 1.25
      g63:
        x: -0.1
        y: -3.05
        h: 1.25
      g64:
        x: -0.1
        y: -3.95
        h: 1.25
      g65:
        x: -0.1
        y: -4.85
        h: 1.25
      g66:
        x: -0.1
        y: -5.8
        h: 1.25
